name: smalltalkCI
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        smalltalk:
          - Squeak64-5.3
          - Squeak64-5.2
          - Squeak64-5.1
          - Squeak64-trunk
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: hpi-swa/setup-smalltalkCI@v1
      id: smalltalkci
      with:
        smalltalk-version: ${{ matrix.smalltalk }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-version }}
      timeout-minutes: 15
    - run: echo "::set-env name=SCI_COVERAGE_FILE_LOCATION::${HOME}/.smalltalkCI/_builds/coveralls_results.json"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        file: ${{ env.SCI_COVERAGE_FILE_LOCATION }}
